const express = require("express");
const https = require("https");
const router = express.Router();
const { flickrImages } = require("../services/flickrApi");

var randomThemes=[
    "neverland",
    "taylor swift",
    "selena gomez",
    "puppy",
    "cat",
    "kitten",
    "dog",
    "flower",
    "bees",
    "book",
    "robot",
    "computer",
    "car",
    "love",
    "mexico",
    "australia",
    "games",
    "music",
    "dance",
    "justin bieber",
    "lady gaga",
    "barbie",
    "sponge bob",
    "elmo",
    "superman",
    "spiderman",
    "jungle",
    "batman",
    "ironman",
    "joker",
    "penguin",
    "bird",
    "kangaroo",
    "tiger",
    "lion",
    "bear",
    "spring",
    "nature",
    "nintendo",
    "art",
    "paint",
    "food",
    "pizza",
    "soup",
    "restaurant",
    "bread",
    "summer",
    "turtle",
    "ocean",
    "octopus",
    "party",
    "panda",
    "forest",
    "sushi",
    "cosplay",
    "ice cream",
    "ice",
    "hockey",
    "soccer",
    "marathon",
    "guitar",
    "piano",
    "star wars",
    "toy story 2",
    "toy story",
    "Afghanistan","Albania","Algeria","Andorra","Angola","Anguilla", "Argentina",
    "Armenia","Australia","Austria","Bahamas","Bahrain","Bangladesh","Barbados","Belarus","Belgium",
    "Belize","Bolivia","Brazil","British Virgin Islands",
    "Bulgaria","Cambodia","Chad","Chile","China",
    "Colombia","Congo","Cook Islands","Costa Rica","Croatia","Cuba","Czech Republic",
    "Denmark","Dominica","Dominican Republic","Ecuador","Egypt","El Salvador","Estonia","Ethiopia",
    "Fiji","Finland","France","French Polynesia",
    "Germany","Ghana","Gibraltar","Greece","Greenland","Grenada","Guam","Guatemala","Guernsey","Guinea","Guinea Bissau","Guyana",
    "Haiti","Honduras","Hong Kong","Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland","Isle of Man","Israel","Italy",
    "Jamaica","Japan","Jersey","Jordan","Kazakhstan","Kenya","Kuwait","Kyrgyz Republic","Laos","Latvia","Lebanon","Lesotho","Liberia",
    "Libya","Liechtenstein","Lithuania","Luxembourg","Macau","Macedonia","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta",
    "Mauritania","Mauritius","Mexico","Moldova","Monaco","Mongolia","Montenegro","Montserrat","Morocco","Mozambique","Namibia",
    "Nepal","Netherlands","Netherlands Antilles","New Caledonia","New Zealand","Nicaragua","Niger","Nigeria","Norway","Oman","Pakistan",
    "Palestine","Panama","Papua New Guinea","Paraguay","Peru","Philippines","Poland","Portugal","Puerto Rico","Qatar","Reunion","Romania",
    "Russia","Rwanda","Samoa","San Marino","Satellite","Saudi Arabia","Senegal","Serbia","Seychelles",
    "Sierra Leone","Singapore","Slovakia","Slovenia","South Africa","South Korea","Spain","Sri Lanka","St Lucia",
    "St Vincent","Sudan","Suriname","Swaziland","Sweden","Switzerland","Syria","Taiwan","Tajikistan","Tanzania","Thailand",
    "Togo","Tonga","Tunisia","Turkey","Turkmenistan","Uganda","Ukraine",
    "United Arab Emirates","United Kingdom","Uruguay","Uzbekistan","Venezuela","Vietnam","Yemen","Zambia","Zimbabwe",
    "Aaliyah", "Abraham Lincoln","Adam DeVine", 
    "Adam Driver", "Adam Levine", "Adam Sandler", "Addison Rae", "Adele", "Alan Walker", "Albert Einstein",  "Alec Baldwin", 
    "Alex Choi", "Alexa Chung", "Alexa Demie", "Alexander Hamilton", "Alexandra Cooper", "Alice Cooper", "Alicia Keys", 
     "Amy Schumer", "Amy Winehouse", 
     "Angelina Jolie","Anna Faris",
    "Ariana Grande", "Arnold Schwarzenegger", 
    "ASAP Rocky", "Ashley Graham",  "Ashton Kutcher", "Aurora", "Ava Max","Avril Lavigne", 
    "Backstreet Boys", "Bad Bunny",  "Barack Obama", 
    "Beethoven",  "Bella Hadid", "Bella Thorne", "Belle Delphine", "Ben Affleck", "Ben Carson", 
    "Ben Shapiro", "Bernie Sanders", 
    "Big Sean",  "Bill Clinton", "Bill Gates", "Bill Murray", "Bill Nye", "Billie Eilish", "Billy Joel", 
    "Billy Ray Cyrus", "Blackbear", "Blackpink", "Blake Lively",  
    "Bob Dylan", "Bob Marley", "Bob Ross",  "Brad Paisley", "Brad Pitt", 
    "Brendon Urie", "British Royal Family", 
    "Britney Spears", "Bruce Jenner", "Bruce Lee", "Bruce Springsteen", "Bruce Willis", "Bruno Mars",
    "BTS", "Bubba Wallace", "Calum Scott", "Calvin Harris", "Calvin Johnson", "Cameron Boyce", "Cameron Diaz", 
    "Camila Cabello", "Camila Mendes", "Cardi B", "Carly Rae Jepsen", 
    "Celine Dion", "Chance The Rapper", "Charlie Chaplin",  "Charlie Puth", 
    "Childish Gambino", "Chris Brown", "Chris Evans", "Chris Hemsworth",
     "Chris Pratt", "Chris Rock", "Chrissy Teigen", "Christian Bale", "Christiano Ronaldo", 
   "Christina Aguilera", "Christina Perri","Christopher Columbus", 
    "Clint Eastwood", "Cody Simpson", "Coldplay",
    "Cole Sprouse", "Conor McGregor", 
    "Courtney Cox",
    "Daniel Craig", "Daniel Radcliffe", "Danielle Cohn", "Danny Devito", "Danny Glover",
     "David Bowie", 
    "David Dobrik", 
    "Deana Carter","Demi Lovato","Diana Ross",  
    "DJ Khaled", "Doja Cat", "Dolly Parton", "Donald Trump", 
    "Drake", "Dua Lipa", "Dylan Sprouse", "Ed Sheeran", "Eddie McGuire", "Eddie Murphy", 
    "Elizabeth Olsen", "Elizabeth Taylor", "Elizabeth Warren", "Ellen Degeneres", 
    "Ellen Pompeo", "Ellie Goulding", "Elon Musk", "Elton John", "Elvis", "Emilia Clarke", "Emily Ratajkowski", "Eminem",  
    "Emma Chamberlain", "Emma Roberts", "Emma Stone", "Emma Watson", 
     "Eva Mendes", "EXO", "Fifth Harmony", 
    "Floyd Mayweather", "Frank Ocean", "Frank Sheeran", "Frank Sinatra", "Frankie Grande", 
    "Freddie Mercury", "Frederick Douglass", "Future", "Gal Gadot", 
    "George Bush", "George Clooney", "George Lucas", 
    "Versace", "Gigi Hadid", "Gordon Ramsay", 
    "Gorillaz", "Grace VanderWaal", "Grant Achatz", "Grant Cardone", "Green Day", "Greg Fishel", "Greta Thunberg", "Grimes", 
    "Gus Kenworthy", "Gwen Stefani", "Gwyneth Paltrow", "Haikyuu", "Haile Selassie", "Hailee Steinfeld", "Hailey Baldwin", "Hailey Bieber", 
    "Halsey", "Hannah Margaret Selleck", "Harper Lee", "Harriet Tubman", "Harrison Ford", "Harry Styles", "Helen Hunt", "Helen Keller", 
    "Henry Cavill", "Henry Ford", "Henry Winkler", "Hilary Duff", "Hillary Clinton", "Howard Hughes", "Howard Stern", "Hrithik Roshan", 
    "Hugh Grant", "Hugh Hefner", "Hugh Jackman", "Hunter Hayes", "Ian Poulter", "Ian Somerhalder", "Ice Cube", "Idris Elba", "Iggy Azalea", 
    "Imagine Dragons", "Irwin Winkler", "Isaac Newton", "Isaak Presley", "Ivan Moody", "Ivanka Trump", "Jack Black", "Jack Nicholson", 
    "Jack Nicklaus", "Jackie Chan", "Jackie Robinson", "Jackson Pollock", "Jacob Elordi", "Jacob Sartorius", "Jada Pinkett Smith", 
    "Jaden Smith", "Jake Gyllenhaal", "Jake Paul", "Jamal Murray", "James Charles", "James Corden", "James Dean", "James Franco", "James Garner", 
    "James Harden", "James Madison", "Jamie Foxx", "Jamie Lee Curtis", "Jamie Lynn Spears", "Jamie Oliver", "Jane Fonda", "Jason Aldean", 
    "Jason Bateman", "Jason Derulo", "Jason Garrett", "Jason Momoa", "Jason Statham", "Jay Gould", "Jay Leno", "Jayme Closs", "Jeff Bezos", 
    "Jeff Goldblum", "Jeffree Star", "Jenna Coleman", "Jenna Marbles", "Jennette McCurdy", "Jennifer Aniston", "Jennifer Garner", "Jennifer Hudson", 
    "Jennifer Lawrence", "Jennifer Lopez", "Jenny McCarthy", "Jeremy Bamber", "Jeremy Clarkson", "Jeremy Lin", "Jerry Jones", "Jerry Seinfeld", 
    "Jesse Owens", "Jessica Alba", "Jill Wagner", "Jillie Mack", "Jim Carrey", "Jim Nabors", "Jim Walton", "Jimi Hendrix", "Jimmy Buffet", 
    "Jimmy Carter", "Jimmy Fallon", "Jimmy Kimmel", "Joanna Gaines", "Joaquin Phoenix", "Joe Biden", "Joe Jonas", "Joe Lacob", "Joe Rogan", 
    "Joel Embiid", "Joel Kinnaman", "Joel Osteen", "Joey Fatone", "Joey Klaasen", "John Candy", "John Cena", "John Krasinski", 
    "John Legend", "John Lennon", "John Mayer", "John Muir", "John Travolta", "John Wayne", "John Wayne Gacy", "Johnny Carson", "Johnny Cash", 
    "Johnny Depp", "Jon Stewart", "Jonah Hill", "Jonas Brothers", "Jordan Belfort", "Joseph Haydn", "Josh Groban", "Joyner Lucas", "Judi Dench", 
    "Judy Garland", "Juice WRLD", "Julia Fox", "Julia Roberts", "Julie Andrews", "Julie Chrisley", "June Carter", "Jungkook", "Justice Smith", 
    "Justin Bieber", "Justin Timberlake", "Justin Trudeau", "Justina Machado", "Kai Knapp", "Kaley Cuoco", "Kamala Harris", 
    "Kane Brown", "Kanye West", "Kate Chastain", "Kate McKinnon", "Kate Middleton", "Kate Winslet", "Katherine Jenkins", "Katherine Johnson", 
    "Katherine Schwarzenegger", "Katie Lee", "Katie Price", "Katy Perry", "Kawhi Leonard", "Keanu Reeves", "Keemstar", "Keith Urban", 
    "Kelly Clarkson", "Kelly Ripa", "Kelsey Grammer", "Ken Jennings", "Kendall Jenner", "Kendrick Lamar", "Kenny Chesney", "Kerry Washington", 
    "Kesha", "Kevin Bacon", "Kevin Costner", "Kevin Durant", "Kevin Gates", "Kevin Hart", "Khalid", "Khloe Kardashian", "Kid Rock", 
    "Kim Kardashian", "Kobe Bryant", "Kodak Black", "Kourtney Kardashian", "Kris Jenner", "Kristen Bell", "Kristen Stewart", "Kurt Cobain", 
    "Kyla Weber", "Kyle Busch", "Kyle Cooke", "Kyle Richards", "Kylie Jenner", "La La Anthony", "Lacey Evans", "Lady Gaga", "Lake Bell", 
    "Lamar Jackson", "Lana Candor", "Lana Del Rey", "Larry Bird", "Larry David", "Laura Prepon", "Lauren Bushnell", "Lauren Daigle", 
    "Lauren London", "LaVar Ball", "LazarBeam", "LeBron James", "Led Zeppelin", "Lei Li Keenan", "Lenny Kravitz", "Leonardo da Vinci", 
    "Leonardo DiCaprio", "Lew Alcindor", "Lewis Capaldi", "Lewis Hamilton", "Liam Hemsworth", "Liam Neeson", "Liam Payne", "Liberace", 
    "Lil Baby", "Lil Dicky", "Lil Nas X", "Lil Peep", "Lil Pump", "Lil Uzi Vert", "Lil Wayne", "Lil Yachty", "Lili Reinhart", "Lindsay Wagner", 
    "Lindsey Vonn", "Linkin Park", "Lionel Messi", "Lisa Bonet", "Lisa Vanderpump", "Little Mix", "Lizzo", "Logan Paul", "Logic", "Lorde", 
    "Lori Loughlin", "Louis Partridge", "Louis Tomlinson", "Luke Bryan", "Luke Combs", "Luke Kuechly", "Mac Miller", "Macaulay Culkin", 
    "Machine Gun Kelly", "Macklemore", "Madelyn Cline", "Madison Beer", "Madonna", "Magic Johnson", "Malcolm X", "Manny Khoshbin", 
    "Marcus Freeman", "Marcus Lemonis", "Mariah Carey", "Marie Osmond", "Marilyn Monroe", "Mark Cuban", "Mark Harmon", "Mark Richt", 
    "Mark Ruffalo", "Mark Twain", "Mark Wahlberg", "Mark Zuckerberg", "Maroon 5", "Marshawn Lynch", "Marshmello", "Martha Stewart", 
    "Martin Kemp", "Martin Lawrence", "Martina McBride", "Marvin Sapp", "Mary Fitzgerald", "Mary Lee Pfeiffer", "Mat Fraser", "Matt Damon", 
    "Matt Lauer", "Matt LeBlanc", "Matt Ryan", "Matt Stonie", "Matthew Garber", "Max Verstappen", "Maya Angelou", "Maya Hawke", "Meat Loaf", 
    "Meek Mill", "Megan Fox", "Megan Thee Stallion", "Meghan Markle", "Meghan Trainor", "Melania Trump", "Melanie Iglesias", "Melanie Martinez", 
    "Melinda Gates", "Melissa McCarthy", "Meryl Streep", "Metallica", "Michael Jackson", "Michael Jordan", 
     "Michael Phelps", "Michelangelo", "Michelle Obama", "Migos",
    "Mikaela Shiffrin", "Mike Epps", "Mike Patton", "Mike Pence", "Mike Rowe", "Mike Tyson", "Mila Kunis", "Miley Cyrus", "Millie Bobby Brown", 
    "Minnie Driver", "Miranda Lambert", "Missy Elliott", "Morgan Freeman", "Mossimo Giannulli", "Mozart", "MrBeast", "Naira Marley", 
    "Nancy Pelosi", "Naomi Osaka", "Naomi Scott", "Nas", "Natalie Portman", "Neil Armstrong", "Neil Young", "Nelly", "Nelson Mandela", 
    "Neymar", "Niall Horan", "Nick Jonas", "Nicki Minaj",  "Nicolas Cage", 
     "Nicole Kidman","Tesla", "Nina Dobrev", "Olivia Colman", 
    "Olivia Wilde",  "One Direction", "Oprah Winfrey", 
    "Orlando Bloom", "Oscar Wilde", "Owen Wilson", "Ozzy Osbourne", "Pablo Neruda", "Pablo Picasso",  "Panic! at the Disco", 
    "Paris Hilton", "Paris Jackson",  "Patrick Stewart", 
    "Paul McCartney", "Paul Rudd", "Paul Walker",
     "Pete Davidson", "PewDiePie",
    "Pink", "Pitbull", "Post Malone", "Prince", "Prince Harry", "Prince William", "Princess Diana", 
    "Priyanka Chopra", "Queen", "Queen Elizabeth", "Quentin Tarantino", 
    "Rebel Wilson", 
    "Reese Witherspoon",
    "Rihanna", 
    "Rita Ora","Robert De Niro",
    "Robert Kraft", "Robert Pattinson", "Robert Redford", "Robin Thicke", "Robin Williams", 
    "Ronald Reagan", "Rosa Parks", "RuPaul", 
    "Ryan Gosling", "Ryan Reynolds", "Sabrina Carpenter", 
    "Sam Smith", 
    "Sandra Bullock", "Sandra Cisneros", "Sara Evans", "Saweetie", "Scarlett Johansson", 
    "Scooter Braun", "Scott Eastwood", "Selena Gomez", "Selena", 
    "Serena Williams", "Shakespeare", "Shakira",
    "Shawn Mendes", "Sia", "Simon Cowell", "Simone Biles", "Skai Jackson", "Snoop Dogg", "Sofia Vergara", "Sophie Turner", 
    "Soulja Boy", "SSundee", "Stan Lee", "Stephen Colbert", "Stephen King", 
    "Steve Harvey", "Steve Irwin", "Steve Jobs", "Steven Spielberg", 
    "Stevie Wonder", "Sydney Sweeney", "Sylvester Stallone", 
    "Taylor Swift", "Ted Bundy",
    "The ACE Family", "The Beatles", "The Chainsmokers", "The Jackson 5", "The Kardashians", 
    "The Rolling Stones", "The Weeknd", "Thomas Edison", 
    "TikTok", "Tim Allen", "Tim McGraw", "Timothée Chalamet", 
    "Tom Brady", "Tom Cruise",  "Tom Hanks", "Tom Hardy", "Tom Holland", 
    "Tommy Wiseau", "Tony Lopez",  "Tory Lanez",
    "Travis Scott", "Tupac", "Twenty One Pilots", 
    "U2","Usain Bolt", "Usher",  "Vanessa Bryant", 
    "Vanessa Hudgens", "Victoria Beckham", "Vin Diesel", "Vincent Van Gogh", 
    "Walt Disney",
    "Wendy Williams", "Whitney Houston", "Will Ferrell","Will Smith",
    "Wiz Khalifa", "XXXTentacion",
    "Young Thug", "Yung Gravy", "Yungblud", "Zac Efron","Zara Larsson", "Zayn Malik", 
     "Zendaya", 
    ];
function random_item(randomThemes)
{
  
return encodeURI(randomThemes[Math.floor(Math.random()*randomThemes.length)]);
     
}

// Route
router.get("/", async (req, res) => {
  theme = random_item(randomThemes).toLowerCase();
  cardKey = `CardKey:${theme}`;
  flickrImages(res, theme, cardKey);
});


module.exports = router;