const express = require("express");
const https = require("https");
const router = express.Router();
const { flickrImages } = require("../services/flickrApi");

var randomThemes=[
    "neverland",
    "taylor swift",
    "selena gomez",
    "puppy",
    "cat",
    "kitten",
    "dog",
    "flower",
    "bees",
    "book",
    "robot",
    "computer",
    "car",
    "love",
    "mexico",
    "australia",
    "games",
    "music",
    "dance",
    "justin bieber",
    "lady gaga",
    "barbie",
    "sponge bob",
    "elmo",
    "superman",
    "spiderman",
    "jungle",
    "batman",
    "ironman",
    "joker",
    "penguin",
    "bird",
    "kangaroo",
    "tiger",
    "lion",
    "bear",
    "spring",
    "nature",
    "nintendo",
    "art",
    "paint",
    "food",
    "pizza",
    "soup",
    "restaurant",
    "bread",
    "summer",
    "turtle",
    "ocean",
    "octopus",
    "party",
    "panda",
    "forest",
    "sushi",
    "cosplay",
    "ice cream",
    "ice",
    "hockey",
    "soccer",
    "marathon",
    "guitar",
    "piano",
    "star wars",
    "toy story 2",
    "toy story",
    "Afghanistan","Albania","Algeria","Andorra","Angola","Anguilla", "Argentina",
    "Armenia","Aruba","Australia","Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh","Barbados","Belarus","Belgium",
    "Belize","Benin","Bermuda","Bhutan","Bolivia","Botswana","Brazil","British Virgin Islands",
    "Brunei","Bulgaria","Burkina Faso","Burundi","Cambodia","Cameroon","Cape Verde","Cayman Islands","Chad","Chile","China",
    "Colombia","Congo","Cook Islands","Costa Rica","Cote D Ivoire","Croatia","Cruise Ship","Cuba","Cyprus","Czech Republic",
    "Denmark","Djibouti","Dominica","Dominican Republic","Ecuador","Egypt","El Salvador","Equatorial Guinea","Estonia","Ethiopia",
    "Falkland Islands","Faroe Islands","Fiji","Finland","France","French Polynesia","French West Indies","Gabon","Gambia","Georgia",
    "Germany","Ghana","Gibraltar","Greece","Greenland","Grenada","Guam","Guatemala","Guernsey","Guinea","Guinea Bissau","Guyana",
    "Haiti","Honduras","Hong Kong","Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland","Isle of Man","Israel","Italy",
    "Jamaica","Japan","Jersey","Jordan","Kazakhstan","Kenya","Kuwait","Kyrgyz Republic","Laos","Latvia","Lebanon","Lesotho","Liberia",
    "Libya","Liechtenstein","Lithuania","Luxembourg","Macau","Macedonia","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta",
    "Mauritania","Mauritius","Mexico","Moldova","Monaco","Mongolia","Montenegro","Montserrat","Morocco","Mozambique","Namibia",
    "Nepal","Netherlands","Netherlands Antilles","New Caledonia","New Zealand","Nicaragua","Niger","Nigeria","Norway","Oman","Pakistan",
    "Palestine","Panama","Papua New Guinea","Paraguay","Peru","Philippines","Poland","Portugal","Puerto Rico","Qatar","Reunion","Romania",
    "Russia","Rwanda","Samoa","San Marino","Satellite","Saudi Arabia","Senegal","Serbia","Seychelles",
    "Sierra Leone","Singapore","Slovakia","Slovenia","South Africa","South Korea","Spain","Sri Lanka","St Lucia",
    "St Vincent","Sudan","Suriname","Swaziland","Sweden","Switzerland","Syria","Taiwan","Tajikistan","Tanzania","Thailand",
    "Togo","Tonga","Tunisia","Turkey","Turkmenistan","Uganda","Ukraine",
    "United Arab Emirates","United Kingdom","Uruguay","Uzbekistan","Venezuela","Vietnam","Yemen","Zambia","Zimbabwe",
    "Aaliyah", "Aaron Hernandez", "Aaron Judge", "Aaron Lewis", "Aaron Paul", "Aaron Rodgers", "ABBA", "Abraham Lincoln","Adam DeVine", 
    "Adam Driver", "Adam Levine", "Adam Sandler", "Addison Rae", "Adele", "Al Gore", "Alan Walker", "Albert Einstein", "Albert Lin", "Alec Baldwin", 
    "Alex Choi", "Alexa Chung", "Alexa Demie", "Alexander Hamilton", "Alexandra Cooper", "Alice Cooper", "Alicia Keys", 
    "Allen Iverson", "Allison Holker", "Allison Stokke", "Amal Clooney", "Amelia Earhart", "Amy Klobuchar", "Amy Schumer", "Amy Winehouse", 
    "Anderson Paak", "Anderson Cooper", "Andrew Cuomo", "Andrew East", "Andrew Yang", "Andy Warhol", "Angelina Jolie", "Angie Varona", "Anna Faris",
    "Annie LeBlanc", "Anthony Hopkins", "Anthony Joshua", "Anthony Rizzo", "Anwar Hadid", "Ariana Grande", "Arnold Palmer", "Arnold Schwarzenegger", 
    "Arthur Blank", "ASAP Rocky", "Ashley Graham", "Ashley McBryde", "Ashton Kutcher", "Aurora", "Ava Max", "Avani Gregg", "Avril Lavigne", 
    "Axl Rose", "Ayesha Curry", "Babe Ruth", "Backstreet Boys", "Bad Bunny", "Bailey Sarian", "Bam Margera", "Banksy", "Barack Obama", 
    "Barry Weiss", "Bear Grylls", "Beethoven", "Behati Prinsloo", "Bella Hadid", "Bella Thorne", "Belle Delphine", "Ben Affleck", "Ben Carson", 
    "Ben Mallah", "Ben Shapiro", "Ben Stiller", "Bernard Arnault", "Bernie Mac", "Bernie Sanders", "Betsy DeVos",
    "Big Sean", "Biggie Smalls", "Bill Clinton", "Bill Gates", "Bill Maher", "Bill Murray", "Bill Nye", "Billie Eilish", "Billy Joel", 
    "Billy Ocean", "Billy Porter", "Billy Ray Cyrus", "Blackbear", "Blackpink", "Blake Lively", "Blake Shelton", "Blog", "Blueface", 
    "Bob Corker", "Bob Dylan", "Bob Keeshan", "Bob Marley", "Bob Ross", "Bobby Flay", "Bode Miller", "Bono", "Brad Paisley", "Brad Pitt", 
    "Brady Quinn", "Brandi Glanville", "Brantley Gilbert", "Brendon Urie", "Brett Young", "Bridgette Doremus", "British Royal Family", 
    "Britney Spears", "Brittany Murphy", "Brody Jenner", "Bruce Jenner", "Bruce Lee", "Bruce Springsteen", "Bruce Willis", "Bruno Mars",
    "Bryson DeChambeau", "BTS", "Bubba Wallace", "Calum Scott", "Calvin Harris", "Calvin Johnson", "Cameron Boyce", "Cameron Diaz", 
    "Camila Cabello", "Camila Mendes", "Cardi B", "Carl Edwards", "Carly Rae Jepsen", "Carrie Underwood", "Cary Grant", "Casey Neistat", 
    "Celine Dion", "Chance The Rapper", "Charles Leclerc", "Charlie Chaplin", "Charlie Daniels", "Charlie Puth", "Chase Stokes", "Cheryl Ladd", 
    "Childish Gambino (Donald Glover)", "Chip Gaines", "Chris Brown", "Chris Evans", "Chris Farley", "Chris Hemsworth", "Chris Lane", 
    "Chris McCandless", "Chris Pratt", "Chris Rock", "Chris Watts", "Chris Young", "Chrissy Teigen", "Christian Bale", "Christiano Ronaldo", 
    "Christie Brinkley", "Christina Aguilera", "Christina Perri", "Christina Ricci", "Christine Quinn", "Christopher Columbus", 
    "Christopher Reeve", "Chuck Berry", "Chuck Schumer", "Ciara Wilson", "Clint Eastwood", "Cody Simpson", "Coldplay", "Cole LaBrant", 
    "Cole Sprouse", "Colin Firth", "Colin Kaepernick", "Condoleezza Rice", "Connor Cruise", "Conor McGregor", "Corey Taylor", "Cornel West", 
    "Cory Booker", "Cory Monteith", "Courtney Cox", "Cuco", "Dale Earnhardt", "Dallmyd", "Dan Bilzerian", "Dan Crenshaw", "Dan Lok", "Dan Peña", 
    "Dana White", "Danica Patrick", "Daniel Craig", "Daniel Radcliffe", "Danielle Cohn", "Danny Devito", "Danny Glover", "Danny Koker", 
    "Danny Thomas", "DanTDM", "Darrell Issa", "Dave Chappelle", "Dave Ramsey", "David Attenborough", "David Bowie", "David Brinkley", 
    "David Cassidy", "David Dobrik", "David Furnish", "David Muir", "David Portnoy", "Davina McCall", "Deadmau5", "Dean Martin", 
    "Deana Carter", "Deftones", "Demi Lovato", "Dennis Rodman", "Denzel Washington", "Diana Ross", "Diane Ladd", 
    "DJ Khaled", "DJ Kool Herc", "Doja Cat", "Dolly Parton", "Don Lemon", "Donald Trump", "Douglas Brinkley",
    "Drake", "Drew Carey", "Dua Lipa", "Dylan Sprouse", "Ed Sheeran", "Eddie Hall", "Eddie McGuire", "Eddie Murphy", 
    "Eddie Redmayne", "Eddie Van Halen", "Edie Falco", "Elizabeth Olsen", "Elizabeth Taylor", "Elizabeth Warren", "Ellen Degeneres", 
    "Ellen Pompeo", "Ellie Goulding", "Elon Musk", "Elton John", "Elvis", "Emilia Clarke", "Emily Ratajkowski", "Eminem", "Emma Barton", 
    "Emma Chamberlain", "Emma Roberts", "Emma Stone", "Emma Watson", "Eric Clapton", "Eric Porterfield", "Ernest Hemingway", "Ethan Hawke", 
    "Ethan Suplee", "Eva Mendes", "EXO", "Faith Hill", "Fetty Wap", "Fifth Harmony", "Finn Wolfhard", "Florida Georgia Line", 
    "Floyd Mayweather", "Forrest Fenn", "Foster the People", "Frank Ocean", "Frank Sheeran", "Frank Sinatra", "Frankie Grande", 
    "Fred Rogers", "Fred Stoller", "Freddie Mercury", "Frederick Douglass", "Future", "Gal Gadot", "Garth Brooks", "Gary Sinise", 
    "Gary Vaynerchuk", "Gavin Newsom", "George Bush", "George Clooney", "George Ezra", "George Harrison", "George Lucas", 
    "George Michael", "George Strait", "George Washington", "Gianni Versace", "Gigi Hadid", "Goldie Hawn", "Gordon Ramsay", 
    "Gorillaz", "Grace VanderWaal", "Grant Achatz", "Grant Cardone", "Green Day", "Greg Fishel", "Greta Thunberg", "Grimes", 
    "Gus Kenworthy", "Gwen Stefani", "Gwyneth Paltrow", "Haikyuu", "Haile Selassie", "Hailee Steinfeld", "Hailey Baldwin", "Hailey Bieber", 
    "Halsey", "Hannah Margaret Selleck", "Harper Lee", "Harriet Tubman", "Harrison Ford", "Harry Styles", "Helen Hunt", "Helen Keller", 
    "Henry Cavill", "Henry Ford", "Henry Winkler", "Hilary Duff", "Hillary Clinton", "Howard Hughes", "Howard Stern", "Hrithik Roshan", 
    "Hugh Grant", "Hugh Hefner", "Hugh Jackman", "Hunter Hayes", "Ian Poulter", "Ian Somerhalder", "Ice Cube", "Idris Elba", "Iggy Azalea", 
    "Imagine Dragons", "Irwin Winkler", "Isaac Newton", "Isaak Presley", "Ivan Moody", "Ivanka Trump", "Jack Black", "Jack Nicholson", 
    "Jack Nicklaus", "Jackie Chan", "Jackie Robinson", "Jackson Pollock", "Jacob Elordi", "Jacob Sartorius", "Jada Pinkett Smith", 
    "Jaden Smith", "Jake Gyllenhaal", "Jake Paul", "Jamal Murray", "James Charles", "James Corden", "James Dean", "James Franco", "James Garner", 
    "James Harden", "James Madison", "Jamie Foxx", "Jamie Lee Curtis", "Jamie Lynn Spears", "Jamie Oliver", "Jane Fonda", "Jason Aldean", 
    "Jason Bateman", "Jason Derulo", "Jason Garrett", "Jason Momoa", "Jason Statham", "Jay Gould", "Jay Leno", "Jayme Closs", "Jeff Bezos", 
    "Jeff Goldblum", "Jeffree Star", "Jenna Coleman", "Jenna Marbles", "Jennette McCurdy", "Jennifer Aniston", "Jennifer Garner", "Jennifer Hudson", 
    "Jennifer Lawrence", "Jennifer Lopez", "Jenny McCarthy", "Jeremy Bamber", "Jeremy Clarkson", "Jeremy Lin", "Jerry Jones", "Jerry Seinfeld", 
    "Jesse Owens", "Jessica Alba", "Jill Wagner", "Jillie Mack", "Jim Carrey", "Jim Nabors", "Jim Walton", "Jimi Hendrix", "Jimmy Buffet", 
    "Jimmy Carter", "Jimmy Fallon", "Jimmy Kimmel", "Joanna Gaines", "Joaquin Phoenix", "Joe Biden", "Joe Jonas", "Joe Lacob", "Joe Rogan", 
    "Joel Embiid", "Joel Kinnaman", "Joel Osteen", "Joey Fatone", "Joey Klaasen", "John Candy", "John Cena", "John Krasinski", 
    "John Legend", "John Lennon", "John Mayer", "John Muir", "John Travolta", "John Wayne", "John Wayne Gacy", "Johnny Carson", "Johnny Cash", 
    "Johnny Depp", "Jon Stewart", "Jonah Hill", "Jonas Brothers", "Jordan Belfort", "Joseph Haydn", "Josh Groban", "Joyner Lucas", "Judi Dench", 
    "Judy Garland", "Juice WRLD", "Julia Fox", "Julia Roberts", "Julie Andrews", "Julie Chrisley", "June Carter", "Jungkook", "Justice Smith", 
    "Justin Bieber", "Justin Timberlake", "Justin Trudeau", "Justina Machado", "Kai Knapp", "Kaley Cuoco", "Kamala Harris", 
    "Kane Brown", "Kanye West", "Kate Chastain", "Kate McKinnon", "Kate Middleton", "Kate Winslet", "Katherine Jenkins", "Katherine Johnson", 
    "Katherine Schwarzenegger", "Katie Lee", "Katie Price", "Katy Perry", "Kawhi Leonard", "Keanu Reeves", "Keemstar", "Keith Urban", 
    "Kelly Clarkson", "Kelly Ripa", "Kelsey Grammer", "Ken Jennings", "Kendall Jenner", "Kendrick Lamar", "Kenny Chesney", "Kerry Washington", 
    "Kesha", "Kevin Bacon", "Kevin Costner", "Kevin Durant", "Kevin Gates", "Kevin Hart", "Khalid", "Khloe Kardashian", "Kid Rock", 
    "Kim Kardashian", "Kobe Bryant", "Kodak Black", "Kourtney Kardashian", "Kris Jenner", "Kristen Bell", "Kristen Stewart", "Kurt Cobain", 
    "Kyla Weber", "Kyle Busch", "Kyle Cooke", "Kyle Richards", "Kylie Jenner", "La La Anthony", "Lacey Evans", "Lady Gaga", "Lake Bell", 
    "Lamar Jackson", "Lana Candor", "Lana Del Rey", "Larry Bird", "Larry David", "Laura Prepon", "Lauren Bushnell", "Lauren Daigle", 
    "Lauren London", "LaVar Ball", "LazarBeam", "LeBron James", "Led Zeppelin", "Lei Li Keenan", "Lenny Kravitz", "Leonardo da Vinci", 
    "Leonardo DiCaprio", "Lew Alcindor", "Lewis Capaldi", "Lewis Hamilton", "Liam Hemsworth", "Liam Neeson", "Liam Payne", "Liberace", 
    "Lil Baby", "Lil Dicky", "Lil Nas X", "Lil Peep", "Lil Pump", "Lil Uzi Vert", "Lil Wayne", "Lil Yachty", "Lili Reinhart", "Lindsay Wagner", 
    "Lindsey Vonn", "Linkin Park", "Lionel Messi", "Lisa Bonet", "Lisa Vanderpump", "Little Mix", "Lizzo", "Logan Paul", "Logic", "Lorde", 
    "Lori Loughlin", "Louis Partridge", "Louis Tomlinson", "Luke Bryan", "Luke Combs", "Luke Kuechly", "Mac Miller", "Macaulay Culkin", 
    "Machine Gun Kelly", "Macklemore", "Madelyn Cline", "Madison Beer", "Madonna", "Magic Johnson", "Malcolm X", "Manny Khoshbin", 
    "Marcus Freeman", "Marcus Lemonis", "Mariah Carey", "Marie Osmond", "Marilyn Monroe", "Mark Cuban", "Mark Harmon", "Mark Richt", 
    "Mark Ruffalo", "Mark Twain", "Mark Wahlberg", "Mark Zuckerberg", "Maroon 5", "Marshawn Lynch", "Marshmello", "Martha Stewart", 
    "Martin Kemp", "Martin Lawrence", "Martina McBride", "Marvin Sapp", "Mary Fitzgerald", "Mary Lee Pfeiffer", "Mat Fraser", "Matt Damon", 
    "Matt Lauer", "Matt LeBlanc", "Matt Ryan", "Matt Stonie", "Matthew Garber", "Max Verstappen", "Maya Angelou", "Maya Hawke", "Meat Loaf", 
    "Meek Mill", "Megan Fox", "Megan Thee Stallion", "Meghan Markle", "Meghan Trainor", "Melania Trump", "Melanie Iglesias", "Melanie Martinez", 
    "Melinda Gates", "Melissa McCarthy", "Meryl Streep", "Metallica", "Michael Bloomberg", "Michael Buffer", "Michael Jackson", "Michael Jordan", 
    "Michael Pena", "Michael Phelps", "Michael Strahan", "Michelangelo", "Michelle Obama", "Mick Jagger", "Migos", "Miguel Bezos", 
    "Mikaela Shiffrin", "Mike Epps", "Mike Patton", "Mike Pence", "Mike Rowe", "Mike Tyson", "Mila Kunis", "Miley Cyrus", "Millie Bobby Brown", 
    "Minnie Driver", "Miranda Lambert", "Missy Elliott", "Morgan Freeman", "Mossimo Giannulli", "Mozart", "MrBeast", "Naira Marley", 
    "Nancy Pelosi", "Naomi Osaka", "Naomi Scott", "Nas", "Natalie Portman", "Neil Armstrong", "Neil Young", "Nelly", "Nelson Mandela", 
    "Neymar", "NF", "Niall Horan", "Nick Bolton", "Nick Cannon", "Nick Jonas", "Nicki Minaj", "Nicky Jam", "Nicola Peltz", "Nicolas Cage", 
    "Nicole Fosse", "Nicole Kidman", "Nicole Richie", "Nikki Haley", "Nikola Tesla", "Nina Dobrev", "Novak Djokovic", "NSYNC", "Olivia Colman", 
    "Olivia Culpo","Olivia Wilde", "Olly Murs", "Omar Epps", "One Direction", "Oprah Winfrey", 
    "Orlando Bloom", "Oscar Wilde", "Owen Wilson", "Ozzy Osbourne", "Pablo Neruda", "Pablo Picasso", "Padma Lakshmi", "Panic! at the Disco", 
    "Paris Hilton", "Paris Jackson", "Pat Sajak", "Patrick Dempsey", "Patrick Mahomes", "Patrick Philbin", "Patrick Stewart", "Patrick Swayze", 
    "Paul Hollywood", "Paul McCartney", "Paul Rudd", "Paul Ryan", "Paul Walker", "Pentatonix", "Perrie Edwards", 
    "Pete Buttigieg", "Pete Davidson", "Peter Dinklage", "Peter Falk", "Peter Firth", "Peter Thiel", "PewDiePie", "Peyton Manning", 
    "Phil Mickelson", "Pierce Brosnan", "Pink", "Pitbull", "Post Malone", "Prince", "Prince Harry", "Prince William", "Princess Diana", 
    "Princess Eugenie", "Princess Margaret", "Priyanka Chopra", "Queen", "Queen Elizabeth II", "Queen Latifah", "Quentin Tarantino", 
    "Quinton Reynolds", "Rachel Lindsay", "Rachel Maddow", "Rae Sremmurd", "Rafael Nadal", "Ralph Macchio", "Ramona Singer", 
    "Randy Jackson", "Randy Orton", "Rascal Flatts", "Rashida Jones", "Ray Charles", "Ray Liotta", "Ray Romano", "Rebel Wilson", 
    "Reese Witherspoon", "Reggie Bush", "Reggie Jackson", "Regis Philbin", "Renée Zellweger", "Rhea Perlman", "Richard Branson", 
    "Richard Gere", "Richard Nixon", "Richard Rawlings", "Rick Astley", "Rick Ross", "Rickie Fowler", "Ricky Gervais", "Rihanna", 
    "Rita Ora", "River Phoenix", "Rob Gronkowski", "Rob Halford", "Rob Riggle", "Robert De Niro", "Robert Irvine", 
    "Robert Kraft", "Robert Pattinson", "Robert Redford", "Robin Thicke", "Robin Williams", "Rock Lee", "Roddy Ricch", "Roger Federer",
    "Romain Bonnet", "Ronald Reagan", "Rosa Parks", "Rosemary Clooney", "Ross Kemp", "Ruby Bridges", "Rudy Gobert", "RuPaul", "Rupert Grint", 
    "Russell Westbrook", "Russell Wilson", "Ryan Gosling", "Ryan Reynolds", "Ryan Upchurch", "S Club 7", "Sabrina Carpenter", 
    "Sacha Baron Cohen", "Salvador Dalí", "Sam Darnold", "Sam Elliot", "Sam Hunt", "Sam Querrey", "Sam Smith", 
    "Sammy Sosa", "Sandra Bullock", "Sandra Cisneros", "Sara Evans", "Sasha Calle", "Saweetie", "Scarlett Johansson", 
    "Scooter Braun", "Scott Eastwood", "Scott Yancey", "Scottie Pippen", "Sean Connery", "Selena Gomez", "Selena Green Vargas", 
    "Serena Williams", "Seth Rogen", "Shakespeare", "Shakira", "Shania Twain","Shaun White", "Shawn Johnson", 
    "Shawn Mendes", "Sia", "Simon Cowell", "Simone Biles", "Skai Jackson", "Snoop Dogg", "Sofia Vergara", "Sophia Bush", "Sophie Turner", 
    "Soulja Boy", "SSundee", "Stan Lee", "Stephen 'Twitch' Boss", "Stephen Amell", "Stephen Colbert", "Stephen Curry", "Stephen King", 
    "Steve Ballmer", "Steve Bannon", "Steve Carell", "Steve Harvey", "Steve Irwin", "Steve Jobs", "Steven Seagal", "Steven Spielberg", 
    "Stevie Wonder", "Sue Aikens", "Susan Rice", "Sydney Sweeney", "Sylvester Stallone", "Tai Lopez", 
    "Tammy Hembrow", "Tamron Hall", "Tara Lynn Wilson", "Taylor Hill", "Taylor Mills", "Taylor Swift", "Ted Bundy", "Ted Jorgensen", 
    "Ted Turner", "The ACE Family", "The Beatles", "The Chainsmokers", "The Founding Fathers", "The Jackson 5", "The Kardashians", 
    "The Kennedy Family", "The Koch Brothers", "The Pope", "The Rolling Stones", "The Weeknd", "Thomas Edison", "Tiger Woods", 
    "TikTok", "Tim Allen", "Tim McGraw", "Tim Tebow", "Timothée Chalamet", "Tina Fey", "Tina Turner", "Toby Keith", "Todd Chrisley",
    "Tom Brady", "Tom Clancy", "Tom Cruise", "Tom Ellis", "Tom Felton", "Tom Hanks", "Tom Hardy", "Tom Holland", "Tom Selleck", 
    "Tommy Wiseau", "Tony Curtis", "Tony Lopez", "Tony Robbins", "Tony Romo", "Torrey Devitto", "Tory Lanez", "Trace Adkins", 
    "Travis Scott", "Trevor Noah", "Trevor Wallace", "Trey Songz", "Troy Polamalu", "Tucker Carlson", "Tupac", "Twenty One Pilots", 
    "U2", "UB40", "Uma Thurman", "Una Stubbs", "Upchurch", "Usain Bolt", "Usher", "Valtteri Bottas", "Vanessa Bryant", 
    "Vanessa Hudgens", "Vanna White", "Victor Garber", "Victoria Beckham", "Vin Diesel", "Vince Vaughn", "Vincent Van Gogh", 
    "Walt Disney", "Warren Buffet", "Warren G", "Wayne Brady", "Wayne Carini", "Wayne Gretzky", "Wayne Rooney", 
    "Wendy Williams", "Whitney Houston", "Will Ferrell", "Will Reeve", "Will Smith", "William Shatner", 
    "Willie Nelson", "Wilt Chamberlain", "Winona Ryder", "Wiz Khalifa", "XXXTentacion", "Yael Cohen", "Yamiche Alcindor", 
    "Yara Shahidi", "Young Thug", "Yung Gravy", "Yungblud", "Zac Efron", "Zack Bia", "Zak Bagans", "Zara Larsson", "Zayn Malik", 
    "Zdeno Chara", "Zendaya", "Zion Williamson"
    ];
function random_item(randomThemes)
{
  
return encodeURI(randomThemes[Math.floor(Math.random()*randomThemes.length)]);
     
}

// Route
router.get("/", async (req, res) => {
  theme = random_item(randomThemes);
  cardKey = `CardKey:${theme}`;
  flickrImages(res, theme, cardKey);
});


module.exports = router;